name: Docker

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        env:
          IMAGE_NAME: telecmd
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${{ github.ref_name }} .
          docker push ghcr.io/${{ github.repository }}/${IMAGE_NAME}:${{ github.ref_name }}
